import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillFacebook} from "react-icons/ai";
import Image from "next/image";
import pfp from "../public/tinywow-pfp.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import linktreesite from "../public/linktreesite.png";
import churchsite from "../public/churchsite.png";
import brochuresite from "../public/brochuresite.png";
import resume from "../public/resume.png";
import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Antonio Williams Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
       <section className='min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons dark:text-white'>AntonioWebDev</h1>
          <ul className='flex items-center'>
            <li> <BsFillMoonStarsFill onClick={() => setDarkMode (!darkMode) } className='cursor-pointer text-2xl dark:text-white'/> </li>
            <li> <a className='bg-gradient-to-r from-blue-500 to-cyan-500 text-white px-4 py-2  rounded-md ml-8 text-center' href='https://antoniowilliams-resume.netlify.app/'>Resume</a> </li>
          </ul>
        </nav>
        <div className='text-center p-10 '> 
          <h2 className='text-5xl py-2 text-cyan-600 font-medium md:text-6xl'>Antonio Williams</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and Designer</h3>
          <p className='text-md py-5 leading-8 text-grey-800 md:text-xl maxwidth-xl mx-auto dark:text-white'>Freelancer providing services for web development and needs. Take a look down below at my services and qualifications and let's get you a website!</p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-800'>
          <a href='#'><AiFillTwitterCircle className='dark:text-white'/></a>
          <a href='#'><AiFillLinkedin className='dark:text-white'/></a>
          <a href='#'><AiFillFacebook className='dark:text-white'/></a>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-cyan-500 rounded-full w-80 h-80 mt-20 overflow-hidden '>
         <Image src={pfp}  />
        </div>
        </section>
        <section>
          <div >
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>A fresh pair of eyes in the programming industry I've done work for<span className='text-cyan-500'> churchs</span> and <span className='text-cyan-500'> businesses </span>. some jobs done 100% remotely and and other times I've meet with clients.</p>
          </div>
          <div>
            <div className='text-center
             shadow-lg p-10 rounded-xl my-10 '>
              <span className='flex justify-center'><Image src={design} width={100} height={100} /></span>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className='py-2 dark:text-white'>Creating elegant designs suited for your application needs </p>
              <h4 className='py-4 text-cyan-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-white'>Gimp</p>
              <p className='text-gray-800 py-1 dark:text-white'>Figma</p>
            </div>
          </div>
          <div>
            <div className='text-center
             shadow-lg p-10 rounded-xl my-10 '>
              <span className='flex justify-center'><Image src={consulting} width={100} height={100} /></span>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Consulting</h3>
              <p className='py-2 dark:text-white'>Together we can bring your website ideas to life. </p>
              <h4 className='py-4 text-cyan-600'>Consulting Services</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Planning</p>
              <p className='text-gray-800 py-1 dark:text-white'>Pricing</p>
              <p className='text-gray-800 py-1 dark:text-white'>Drafting</p>
            </div>
          </div>
          <div>
            <div className='text-center
             shadow-lg p-10 rounded-xl my-10 '>
              <span className='flex justify-center'><Image src={code} width={100} height={100} /></span>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Code</h3>
              <p className='py-2 dark:text-white'>Languages and frameworks used to build website </p>
              <h4 className='py-4 text-cyan-600'>Languages I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Html</p>
              <p className='text-gray-800 py-1 dark:text-white'>Css</p>
              <p className='text-gray-800 py-1 dark:text-white'>Javascript</p>
              <p className='text-gray-800 py-1 dark:text-white'>React</p>
              <p className='text-gray-800 py-1 dark:text-white'>Next Js</p>
              <p className='text-gray-800 py-1 dark:text-white'>Tailwind Css</p>
            </div>
          </div>
        </section>
        <section>
          <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
          <p className='dark:text-white'>Here are a few of the <span className='text-cyan-500'>sites </span> that I've worked on over the past few months designed and done by me. Take a look for yourself. Click on the images to visit the websites.</p>
          <div>
            <div className='my-10 shadow-xl'> 
            <h3 className='py-1 font-medium dark:text-white'>Brochure Website</h3>
              <a href='https://trinidad-and-tobago.netlify.app/' target="_blank" ><Image src={brochuresite}/></a>
              </div>
            <div className='my-10 shadow-lg'>
            <h3 className='py-1 font-medium dark:text-white'>Church Website</h3> 
              <a href='https://ccmi-chaguanas.netlify.app/' target="_blank"><Image src={churchsite}/></a>
            </div>
            <div className='mt-10 shadow-lg'> 
            <h3 className='py-1 font-medium dark:text-white'>Linktree Website</h3>
             <a href='https://antonios-linktree-website.netlify.app/' target='_blank'><Image src={linktreesite}/></a>
            </div>
            <div className='mt-10 shadow-lg'> 
            <h3 className='py-1 font-medium dark:text-white'>Resume Website</h3>
             <a href='https://antoniowilliams-resume.netlify.app/' target='_blank'><Image src={resume}/></a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
